# Default values for efk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  appVersion: "6.2.4"

  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
    tag: "6.3.1"
    pullPolicy: "IfNotPresent"

  cluster:
    name: "elasticsearch"
    kubernetesDomain: cluster.local
    # If you want X-Pack installed, switch to an image that includes it, enable this option and toggle the features you want
    # enabled in the environment variables outlined in the README
    xpackEnable: false
    config:
    env:
      # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
      # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
      # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
      MINIMUM_MASTER_NODES: "2"

  client:
    name: client
    replicas: 2
    serviceType: ClusterIP
  ## (dict) If specified, apply these annotations to the client service
  #  serviceAnnotations:
  #    example: client-svc-foo
    heapSize: "512m"
    antiAffinity: "soft"
    nodeSelector: {}
    tolerations: {}
    resources:
      limits:
        cpu: "1"
        # memory: "1024Mi"
      requests:
        cpu: "25m"
        memory: "512Mi"
    priorityClassName: ""
    ## (dict) If specified, apply these annotations to each client Pod
    # podAnnotations:
    #   example: client-foo
    podDisruptionBudget:
      enabled: false
      minAvailable: 1
      # maxUnavailable: 1


  master:
    name: master
    exposeHttp: false
    replicas: 3
    heapSize: "512m"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "4Gi"
      # storageClass: "ssd"
    antiAffinity: "soft"
    nodeSelector: {}
    tolerations: {}
    resources:
      limits:
        cpu: "1"
        # memory: "1024Mi"
      requests:
        cpu: "25m"
        memory: "512Mi"
    priorityClassName: ""
    ## (dict) If specified, apply these annotations to each master Pod
    # podAnnotations:
    #   example: master-foo
    podDisruptionBudget:
      enabled: false
      minAvailable: 2  # Same as `cluster.env.MINIMUM_MASTER_NODES`
      # maxUnavailable: 1

  data:
    name: data
    exposeHttp: false
    replicas: 2
    heapSize: "1536m"
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      name: data
      size: "30Gi"
      # storageClass: "ssd"
    terminationGracePeriodSeconds: 3600
    antiAffinity: "soft"
    nodeSelector: {}
    tolerations: {}
    resources:
      limits:
        cpu: "1"
        # memory: "2048Mi"
      requests:
        cpu: "25m"
        memory: "1536Mi"
    priorityClassName: ""
    ## (dict) If specified, apply these annotations to each data Pod
    # podAnnotations:
    #   example: data-foo
    podDisruptionBudget:
      enabled: false
      # minAvailable: 1
      maxUnavailable: 1

kibana:
  image:
    repository: "docker.elastic.co/kibana/kibana-oss"
    tag: "6.3.1"
    pullPolicy: "IfNotPresent"

  commandline:
    args:

  env:
    # All Kibana configuration options are adjustable via env vars.
    # To adjust a config option to an env var uppercase + replace `.` with `_`
    # Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
    #
    SERVER_PORT: "5601"
    LOGGING_VERBOSE: "true"
    SERVER_DEFAULTROUTE: "/app/kibana"

  service:
    type: NodePort
    externalPort: 443
    internalPort: 5601
    ## External IP addresses of service
    ## Default: nil
    ##
    # externalIPs:
    # - 192.168.0.1
    #
    ## LoadBalancer IP if service.type is LoadBalancer
    ## Default: nil
    ##
    # loadBalancerIP: 10.2.2.2
    annotations:
      # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
      # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
    labels:
      ## Label example: show service URL in `kubectl cluster-info`
      # kubernetes.io/cluster-service: "true"

  ingress:
    enabled: false
    # hosts:
      # - chart-example.local
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    # tls:
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local

  # service account that will run the pod. Leave commented to use the default service account.
  # serviceAccountName: kibana

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 300Mi
    # requests:
    #   cpu: 100m
    #   memory: 300Mi

  priorityClassName: ""

  # Affinity for pod assignment
  # Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # affinity: {}

  # Tolerations for pod assignment
  # Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # Node labels for pod assignment
  # Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  podAnnotations: {}
  replicaCount: 1

fluent-bit:
  # Minikube stores its logs in a separate directory.
  # enable if started in minikube.
  on_minikube: false

  image:
    fluent_bit:
      repository: fluent/fluent-bit
      tag: 0.13.0
    pullPolicy: Always

  # When enabled, exposes json and prometheus metrics on {{ .Release.Name }}-metrics service
  metrics:
    enabled: false
    service:
      port: 2020
      type: ClusterIP

  backend:
    type: es
    forward:
      host: fluentd
      port: 24284
    es:
      host: elasticsearch-client
      port: 9200
      # Elastic Index Name
      index: kubernetes_cluster
      type: flb_type
      logstash_prefix: kubernetes_cluster
      # Optional username credential for Elastic X-Pack access
      http_user:
      # Password for user defined in HTTP_User
      http_passwd:
      # Optional TLS encryption to ElasticSearch instance
      tls: "off"
      tls_verify: "on"
      # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
      tls_ca: ""
      # TLS debugging levels = 1-5
      tls_debug: 1

  parsers:
    ## List the respective parsers in key: value format per entry
    ## Regex required fields are name and regex. JSON required field
    ## is name.
    regex: []
    json: []

    ##
    ## Ref: http://fluentbit.io/documentation/current/output/http.html
    ##
    http:
      host: 127.0.0.1
      port: 80
      uri: "/"
      ## Specify the data format to be used in the HTTP request body
      ## Can be either 'msgpack' or 'json'
      format: msgpack

  env: []

  ## Annotations to add to the DaemonSet's Pods
  podAnnotations: {}

  ## ConfigMap override where fullname is {{.Release.Name}}-{{.Values.existingConfigMap}}
  ## Defining existingConfigMap will cause templates/config.yaml
  ## to NOT generate a ConfigMap resource
  ##
  existingConfigMap: ""

  ## Extra volumes containing additional files required for fluent-bit to work
  ## (eg. CA certificates)
  ## Ref: https://kubernetes.io/docs/concepts/storage/volumes/
  ##
  extraVolumes: []

  ## Extra volume mounts for the fluent-bit pod.
  ## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
  ##
  extraVolumeMounts: []

  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  ## Node tolerations for fluent-bit scheduling to nodes with taints
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  tolerations: []
  # - key: "key"
  #  operator: "Equal|Exists"
  #  value: "value"
  #  effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

  ## Node labels for fluent-bit pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  filter:
    kubeURL: https://kubernetes.default.svc:443
    kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubeTag: kube
  # If true, check to see if the log field content is a JSON string map, if so,
  # it append the map fields as part of the log structure.
  #  mergeJSONLog: true

  # If true, enable the use of monitoring for a pod annotation of
  # fluentbit.io/parser: parser_name. parser_name must be the name
  # of a parser contained within parsers.conf
  #  enableParser: true

  # If true, enable the use of monitoring for a pod annotation of
  # fluentbit.io/exclude: true. If present, discard logs from that pod.
  #  enableExclude: true

  rbac:
    # Specifies whether RBAC resources should be created
    create: true

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    name:
